repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    # - id: no-commit-to-branch
    #   args:
    #     - --pattern=develop|main
    - id: requirements-txt-fixer
    exclude: ^(.vscode/|tests/|core/settings.py|manage.py|env.py|local-only|*.txt|checkout/app.py)


-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
          - --line-length=75
        exclude: ^(.vscode/|tests/|core/settings.py|manage.py|env.py|local-only/|checkout/app.py)
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
# -   repo: https://github.com/PyCQA/pydocstyle
#     rev: 6.1.1
#     hooks:
#     - id: pydocstyle
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.942
#     hooks:
#     - id: mypy
#       additional_dependencies:
#         - types-requests
#       args:
#         - --ignore-missing-imports
# -   repo: https://github.com/PyCQA/pylint
#     rev: v2.13.4
#     hooks:
#     - id: pylint
#       args:
#         - --disable=unused-argument
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args:
        - --in-place
        - --remove-unused-variables
        - --remove-all-unused-imports
      exclude: ^(.vscode/|tests/|core/settings.py|manage.py|env.py|local-only/|checkout/app.py)
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args:
        - --max-line-length=79
        - --max-doc-length=72
        - --ignore=E203,W503
        # D106 Missing docstring in public nested class
        # D401 First line should be in imperative mood
        - --extend-ignore=D106,D401
      exclude: ^(.vscode/|tests/|core/settings.py|manage.py|env.py|local-only/|checkout/app.py)
