# Generated by Django 3.2 on 2022-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='store_description',
            field=models.TextField(help_text="format: required, max_length: 160,  include keywords, discounts,                 or offers you're selling", max_length=160, verbose_name='Store Description'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='store_keywords',
            field=models.TextField(help_text='These are the keywords that your site can be searched with on                Google. Make these single words, relevant to your site,                 often searched', verbose_name='Store Keywords, SEO'),
        ),
    ]
