# Generated by Django 3.2 on 2022-06-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length: 150', max_length=150, verbose_name='category name')),
                ('slug', models.CharField(help_text='format: required, letters, numbers, hyphens, max_length: 200', max_length=200, unique=True, verbose_name='category safe URL')),
                ('category_keywords', models.TextField(help_text='These are the keywords that your site can be searched with on Google. Make these single words, relevant to your site, often searched', verbose_name='Category Keywords, SEO')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length: 150', max_length=150, unique=True, verbose_name='colour name')),
                ('slug', models.CharField(help_text='format: required, letters, numbers, hyphens, max_length: 200', max_length=200, unique=True, verbose_name='colour safe URL')),
            ],
            options={
                'verbose_name': 'Product Colour',
                'verbose_name_plural': 'Product Colours',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='format: required, max_length: 8', max_length=8, verbose_name='product sku')),
                ('name', models.CharField(help_text='format: required, max_length: 150', max_length=150, unique=True, verbose_name='product name')),
                ('description', models.TextField(help_text='format: required, max_length: 1000', verbose_name='product description')),
                ('keywords', models.CharField(help_text='format: required, These are used by Google to search for the product.These are words that are relevant to the product and will be added to the Product Name,and Category Name. Separate words with a comma:turtle, bespoke, etc, max_length: 150', max_length=150, verbose_name='product keywords')),
                ('is_washable', models.BooleanField(default=True, help_text='format: true=yes, false=no', verbose_name='product is washable')),
                ('image', models.ImageField(blank=True, default='images/default/default_image.png', null=True, upload_to='images/products/')),
                ('image_alt_text', models.CharField(help_text='format: required, max_length: 150', max_length=50, verbose_name="alternative text to show if image doesn't load")),
                ('wash_instructions', models.TextField(blank=True, default='Machine washable at 30° (hand-wash or delicate mode).             Gently squeeze out the remaining water using a towel,                 do not wring out, stretch or twist to avoid misshape.                     Dry flat, do not tumble dry.', help_text='Max_length: 1000', null=True, verbose_name='Washing Instructions')),
                ('care_instructions', models.TextField(blank=True, default='This item may include securely fastened safety eyes.             With regular use, these items may require de-pilling.', help_text='Max_length: 1000', null=True, verbose_name='Additional Care instructions')),
                ('weight', models.FloatField(help_text='weight in grams', verbose_name='product weight grams')),
                ('size', models.CharField(help_text='format: product size in CM', max_length=50, verbose_name='product size description in cm')),
                ('unit_cost_price', models.DecimalField(decimal_places=2, error_messages={'name': 'Please enter a valid price'}, help_text='format: max_digits=5, decimal_places=2', max_digits=5, verbose_name='product unit cost price')),
                ('retail_price', models.DecimalField(decimal_places=2, error_messages={'name': 'Please enter a valid price'}, help_text='format: max_digits=5, decimal_places=2', max_digits=5, verbose_name='store retail price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, error_messages={'name': 'Please enter a valid price, max_digits=5, decimal_places=2'}, help_text='format: max_digits=5, decimal_places=2', max_digits=5, null=True, verbose_name='sale price')),
                ('in_stock', models.BooleanField(default=True, help_text='format: true=available, false=sold-out', verbose_name='product stock available')),
                ('is_active', models.BooleanField(default=True, help_text='format: true=active, false=inactive', verbose_name='product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='enter date in format: Y-m-d H:M:S, null-true, blank-true', verbose_name='product created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='enter date in format: Y-m-d H:M:S, null-true, blank-true', verbose_name='product last updated')),
                ('slug', models.CharField(help_text='format: required, letters, numbers, hyphens, max_length: 200', max_length=200, unique=True, verbose_name='product safe URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.colour')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
