# Generated by Django 3.2 on 2022-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default/default_image.webp', upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, help_text='format: true=available, false=sold-out', verbose_name='product stock available'),
        ),
    ]
