# Generated by Django 3.2 on 2022-07-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220714_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default/default_image.webp', upload_to='images/products/'),
        ),
    ]
